# create environment : conda env create -f environment.yml
# update dependencies: conda env update -f environment.yml
# remove environment : conda env remove -n RAiDER
# enter  environment : conda activate RAiDER
# exit   environment : conda deactivate
name: RAiDER
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python>=3
 - cdsapi
 - cfgrib
 - cmake
 - netcdf4
 - cython
 - dask
 - gcc
 - gdal>=3.0
 - h5py
 - jupyterlab
 - libgdal
 - matplotlib
 - numpy
 - pandas
 - pygrib
 - pyproj=1.9.6|>=2.1.0
 - scipy
 - xarray
