# create environment : conda env create -f environment.yml
# update dependencies: conda env update -f environment.yml
# remove environment : conda env remove -n RAiDER
# enter  environment : conda activate RAiDER
# exit   environment : conda deactivate
name: RAiDER
channels:
 - defaults
 - conda-forge
 - anaconda
dependencies:
 - python=3
 - cartopy
 - cdsapi
 - cmake
 - dask
 - gcc
 - h5py
 - krb5
 - matplotlib
 - numpy
 - gdal>=3.0
 - pyproj
 - pygrib
 - scipy
