# create environment : conda env create -f environment.yml
# update dependencies: conda env update -f environment.yml
# remove environment : conda env remove -n RAiDER
# enter  environment : conda activate RAiDER
# exit   environment : conda deactivate
name: RAiDER
channels:
 - conda-forge
 - anaconda
 - defaults
 - psi4
dependencies:
 - python>=3
 - cartopy
 - cdsapi
 - gcc
 - cmake
 - dask
 - h5py
 - krb5
 - matplotlib
 - numpy
 - gdal>=3.0
 - libgdal
 - pyproj
 - pygrib
 - scipy
 - cython
 - jupyterlab
