# create environment : conda env create -f environment.yml
# update dependencies: conda env update -f environment.yml
# remove environment : conda env remove -n RAiDER
# enter  environment : conda activate RAiDER
# exit   environment : conda deactivate
name: RAiDER
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - python>=3
 - cdsapi
 - cfgrib
 - cmake
 - cython
 - dask
 - gcc
 - gdal>=3.0
 - h5py
 - jupyterlab
 - krb5
 - libgdal
 - matplotlib
 - numpy
 - pygrib
 - pyproj=1.9.6 # 2.1.0 should also be ok
 - scipy
 - xarray
